version: '3.8'
services:
  mongo:
    container_name: bunca29
    image: mongo
    environment:
      - MONGO_DATABASE="bunca29"
    ports:
      - 27021:27017
  mongo-express:
    container_name: bunca29-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 3005:8081
